<!-- ========== Refactoring SUMMARY =========== -->

<A NAME="method_summary"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
	<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
	<B>Refactoring Summary</B></FONT></TH>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
	<TD ALIGN="right" VALIGN="top" WIDTH="1%">
	Extract Method refactoring</TD>
	<TD> to reduce the implicit setup to a minimal fixture. </TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%">
Extract Method refactoring</TD>
<TD>to reduce code duplication by using a delegate fixture.</TD>
</TR>
</TABLE>
&nbsp;
<P>