<!-- ========= SETUP DETAIL ======== -->

<A NAME="setup_details"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="6"><FONT SIZE="+2">
<B>Setup Detail $setupSummary$</B></FONT></TH>
</TR>
<tr BGCOLOR="#CCCCFF" CLASS="TableSubHeadingColor">
  <td width= "30%"><b>Fields set in Setup</b></td> 
  <td><img src="../../resources/toolx20.png"></td>
  <td><b>Usage</b></td>
  <td><b>Inherited</b></td>
  <td><b>static</b></td>
  <td><b>Default constructor</b></td>
</tr>

$setupdetailfields$

</table>

&nbsp;
<P>

<HR>