<!-- ========= SETUP DETAIL ======== -->

<A NAME="setup_details"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="6"><FONT SIZE="+2">
<B>Delegate Detail $setupSummary$</B></FONT></TH>
</TR>
<tr BGCOLOR="#CCCCFF" CLASS="TableSubHeadingColor">
  <td width= "30%"><b>Delegate Fields</b></td> 
  <td><b>Inherited</b></td>
  <td><b>static</b></td>
  <td><b>Default constructor</b></td>
</tr>

$delegateFieldsdetail$

</table>

&nbsp;
<P>

<HR>