<!-- ========= Method SUMMARY ======== -->
<H2>Class Cohesion: $LCOM$</H2>
<A NAME="constructor_detail"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="8"><FONT SIZE="+2">
<B>Method Summary</B></FONT></TH>
</TR>
<tr BGCOLOR="#CCCCFF" CLASS="TableSubHeadingColor">
  <td></td> 
  <TH  COLSPAN="4">Fields</th> 
  <th  COLSPAN="3"><b>Setup</b></th>
</tr>
<tr BGCOLOR="#CCCCFF" CLASS="TableSubHeadingColor">
  <td><b>Method name</b></td> 
  <td><img src=$toolIcon$> &nbsp; <b>Total</b></td>  
  <td><b>Delegate</b></td>
  <td><b>Static</b></td>  
  <td><b>Member</b></td>  
  <td><b>Inline</b></td> 
  <td><b>Delegate</b></td>
  <td><b>Params</b></td>
</tr>
$methodSummaryrows$
</table>

&nbsp;
<P>
<HR>